### ISSUE TITLE
Build go binary from Dockerfile, do not install in workflow

### ISSUE THREAD

**Issue by sebastian-sommerfeld-io** [sommerfeld-io/source2adoc#39]
see pipeline.yml

Avoid:

```yml
      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.3
```
